- Tensors are multidimensional arrays.
- Tensors can be one-dimensional. 
- 1-D tensor : scalar number, ie 1,2,3... 
- 2-D tensor : [1,2,3,4]

In [2]:
import tensorflow as tf

2023-12-12 21:56:32.964545: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-12 21:56:32.982059: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-12 21:56:33.116641: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-12 21:56:33.117611: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-12 21:56:33.860257: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [3]:
tensor_zero_d = tf.constant(1)

In [4]:
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [7]:
tensor_3_d = tf.constant([[ [1,2,3],
                            [4,5,6],
                            [7,8,9]    ],
                          [ [10,11,12],
                            [13,14,15],
                            [16,17,18] ]])

print(tensor_3_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3), dtype=int32)


In [8]:
print(tensor_3_d[0])
print(tensor_3_d[0][0])  # [1,2,3]
print(tensor_3_d[0][1])  # [4,5,6]
print(tensor_3_d[0][:,2])  # [3,6,9]

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)


In [9]:
# changing data type
tensor_one_d = tf.constant([1, 2, 3, 4, 5], dtype="float32")
print(tensor_one_d)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [10]:
tensor_one_d = tf.constant([1, 2, 3, 4, 5], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float16)


High speed less resource environment, use less precise data type 

Quantization 

tf.quantization.quantize



This is s test for new monitor setup. 