- Tensors are multidimensional arrays.
- Tensors can be one-dimensional. 
- 1-D tensor : scalar number, ie 1,2,3... 
- 2-D tensor : [1,2,3,4]

In [1]:
import tensorflow as tf

2023-12-11 22:50:33.915311: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-11 22:50:33.932919: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-11 22:50:34.036913: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-11 22:50:34.037598: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-11 22:50:34.714280: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [2]:
tensor_zero_d = tf.constant(1)

In [3]:
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
tensor_two_d = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
